### ISSUE TITLE
Your latest change has spoilt custom training

### ISSUE THREAD

**Issue by Engineer-D** [sovit-123/fasterrcnn-pytorch-training-pipeline#70] opened 2023-05-24 12:34 UTC
Traceback (most recent call last):
  File "/content/fastercnn-pytorch-training-pipeline/train.py", line 542, in <module>
    main(args)
  File "/content/fastercnn-pytorch-training-pipeline/train.py", line 494, in main
    wandb_log(
  File "/content/fastercnn-pytorch-training-pipeline/utils/logging.py", line 185, in wandb_log
    if len(val_pred_image) == 1:
TypeError: object of type 'NoneType' has no len()
wandb: Waiting for W&B process to finish... (failed 1).

this is what I keep getting, I ran it yesterday and it worked today it isn't

**Comment by Engineer-D** [comment] 2023-05-24 12:50
I mean, I reverted to the previous code and it's training now. So something changed in engine.py has definitely affected what's going on in training.py and logging.py. logging.py is where the error is coming from.

**Comment by sovit-123** [comment] 2023-05-24 13:34
Got it, I think I know where the issue lies. I will confirm back here once the issue is fixed.

**Comment by sovit-123** [comment] 2023-05-24 14:21
@Engineer-D It's corrected. You may pull the new code now. 
And please close the issues if it solves the problem.

**Closed** 2023-05-24 15:07 UTC
