### ISSUE TITLE
Mention the erroneous file in the error ValueError: Expected x_min for bbox to be in the range [0.0, 1.0]

### ISSUE THREAD

**Issue by AhmadJamal01** [sovit-123/fasterrcnn-pytorch-training-pipeline#77] opened 2023-06-21 13:20 UTC
Is it possible to add to the error message the file that causes the error?

I am trying to train the model on the RICO dataset from kaggle ( you can find it here https://www.kaggle.com/datasets/onurgunes1993/rico-dataset ) and using colab. The dimensions of each image mentioned in the labels ( 1440 * 2560 ) do not match the actual dimensions when opening the images using openCV ( 1080 * 1920 ).
After converting the labels to Pascal voc format, I have tried rescaling the labels, resizing the images, normalizing the dimensions and deleting the images and labels whose normalized dimensions are not in the range [0,1], but I am still getting the following error
```
Epoch: [0]  [  0/174]  eta: 0:11:26  lr: 0.000007  loss: 3.9243 (3.9243)  loss_classifier: 0.7015 (0.7015)  loss_box_reg: 0.3106 (0.3106)  loss_objectness: 2.6861 (2.6861)  loss_rpn_box_reg: 0.2260 (0.2260)  time: 3.9457  data: 2.4448  max mem: 1315
Traceback (most recent call last):
  File "/content/fasterrcnn-pytorch-training-pipeline/train.py", line 561, in <module>
    main(args)
  File "/content/fasterrcnn-pytorch-training-pipeline/train.py", line 401, in main
    batch_loss_rpn_list = train_one_epoch(
  File "/content/fasterrcnn-pytorch-training-pipeline/torch_utils/engine.py", line 45, in train_one_epoch
    for images, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/content/fasterrcnn-pytorch-training-pipeline/torch_utils/utils.py", line 173, in log_every
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/fasterrcnn-pytorch-training-pipeline/datasets.py", line 327, in __getitem__
    sample = self.transforms(image=image_resized,
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 202, in __call__
    p.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 83, in preprocess
    data[data_name] = self.check_and_convert(data[data_name], rows, cols, direction="to")
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 91, in check_and_convert
    return self.convert_to_albumentations(data, rows, cols)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/bbox_utils.py", line 126, in convert_to_albumentations
    return convert_bboxes_to_albumentations(data, self.params.format, rows, cols, check_validity=True)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/bbox_utils.py", line 394, in convert_bboxes_to_albumentations
    return [convert_bbox_to_albumentations(bbox, source_format, rows, cols, check_validity) for bbox in bboxes]
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/bbox_utils.py", line 394, in <listcomp>
    return [convert_bbox_to_albumentations(bbox, source_format, rows, cols, check_validity) for bbox in bboxes]
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/bbox_utils.py", line 337, in convert_bbox_to_albumentations
    check_bbox(bbox)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/bbox_utils.py", line 421, in check_bbox
    raise ValueError(
ValueError: Expected x_min for bbox (tensor(-0.0028), tensor(0.0527), tensor(0.0021), tensor(0.0891), tensor(1)) to be in the range [0.0, 1.0], got -0.0027777778450399637.
```

**Comment by moste00** [comment] 2023-06-21 21:39
Yes, PLEASE.

I can't count how many times the pipeline crashed with a cryptic "Something is wrong" without telling me the most crucial information : **Where** is that something ?

As a workaround, I have often resorted to writing a custom script that does binary search on the inputs (e.g. feeding 1/2 of the input, seeing if the problem occurs, and eliminating the other half if it does), but that's obviously an ugly hack. 

A much better solution is indeed the pipeline just telling me the erroneous file directly.

**Comment by sovit-123** [comment] 2023-06-22 00:46
Hello @AhmadJamal01 
This is most probably happening because after rescaling some of the bounding boxes have negative dimensions. It will be difficult to right away tell which file causes it when the error is happening because of more than 1 parallel worker in the data loader. However, I may be able to write a simple piece of code that does it before the the image and label data loaders are prepared.

**Comment by AhmadJamal01** [comment] 2023-06-24 13:49
Thank you for your reply, @sovit-123 
By converted dataset, do you mean the dataset only after converting the labels to pascal voc format? Or do you mean the dataset after rescaling the labels as well?

**Comment by sovit-123** [comment] 2023-06-24 14:17
@AhmadJamal01 
I meant rescaling.

**Comment by AhmadJamal01** [comment] 2023-06-24 14:45
@sovit-123 here is a download link to the subset of the dataset I am working with after rescaling and removing the images and labels that have bounding boxes not in the range [0,1]
https://drive.google.com/file/d/1R0J1DIEnuEBfimws2UquBaYLMsGC7vXn/view?usp=sharing

**Comment by sovit-123** [comment] 2023-06-24 15:18
@AhmadJamal01 
Thanks. Can you also add the dataset link without removing the problematic images? Maybe I can reproduce the results and write a script to discard such images on the fly.

**Comment by AhmadJamal01** [comment] 2023-06-24 15:32
Here you go
https://drive.google.com/file/d/1-0zAIZfATDApaYvJ36F9n9T8oS7SRXHk/view?usp=sharing

**Comment by sovit-123** [comment] 2023-06-24 15:36
Thanks.

**Comment by ToufikRahman** [comment] 2023-10-17 04:56
@sovit-123 @AhmadJamal01 
Hi, did anyone find the solution to this problem? I am facing a similar issue.

**Comment by sovit-123** [comment] 2023-10-17 06:43
I am working on this. Will post a solution soon.

**Comment by ToufikRahman** [comment] 2023-10-17 17:20
Okay, thank you. Were you able to recreate the issue? Or should I provide the dataset that is creating the issue?

**Comment by sovit-123** [comment] 2023-10-17 17:29
If you can provide dummy data, it will be easier for me to create a solution for this. Thanks.

**Comment by knoppmyth** [comment] 2024-07-03 07:44
When I encountered this issue, it was due to converting from YOLO format to VOC. I had negative samples in my dataset and during the conversion process, the XML was created with false labelled locations. I was able to see this when I looked at my dataset in labelImg. I ended up removing the negative samples and this resolved the issue.

**Comment by sovit-123** [comment] 2024-08-22 17:26
Hello, I have just pushed an update to `datasets.py` that removes all files with invalid bounding boxes before training. Please check. It also prints the erroneous file names if needed to be manually corrected. 

 I am closing the issue for now. Please re-open if needed.

**Closed by sovit-123** 2024-08-22 17:26 UTC

**Comment by ToufikRahman** [comment] 2024-08-28 19:49
Thank you for the update.
